don't fail when HAFAS returns an Exception
When there are no journeys found, pyHAFAS throws an exception.
Let's catch it, instead of spamming the logs :)

```
2024-10-04 10:16:40.247 ERROR (MainThread) [homeassistant.components.sensor] hafas: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 724, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1300, in async_device_update
    await self.async_update()
  File "/config/custom_components/hafas/sensor.py", line 107, in async_update
    self.journeys = await self.hass.async_add_executor_job(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/deps/lib/python3.12/site-packages/pyhafas/client.py", line 157, in journeys
    res = self.profile.request(body)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/deps/lib/python3.12/site-packages/pyhafas/profile/base/helper/request.py", line 96, in request
    return HafasResponse(res, BaseErrorCodesMapping)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/deps/lib/python3.12/site-packages/pyhafas/types/hafas_response.py", line 30, in __init__
    self.check_for_errors(mapping)
  File "/config/deps/lib/python3.12/site-packages/pyhafas/types/hafas_response.py", line 53, in check_for_errors
    raise mapping[self.data['svcResL'][0]['err']].value(
pyhafas.types.exceptions.JourneysArrivalDepartureTooNearError: HAFAS Kernel: No connection found
```

I've chosen to catch *all* exceptions, as pyhafas Exceptions don't have
any base class (besides Exception) and I thought it's nicer to report no
journeys for any error case.